spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jnu_course_seat_alert?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      table-name: "SPRING_SESSION"
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql

server:
  servlet:
    session:
      timeout: 3000000